spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CarRental
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: dd/MM/yyyy